import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const translations: Record<Language, Record<string, string>> = {
    en: {
      // Dashboard
      dashboard: 'Dashboard',
      welcomeBack: 'Welcome back',
      teamActivity: 'Team Activity',
      activeProjects: 'Active Projects',
      totalClients: 'Total Clients',
      totalEmployees: 'Total Employees',
      pendingTasks: 'Pending Tasks',
      revenueThisMonth: 'Revenue This Month',
      viewActivity: 'View Activity',
      projectStatus: 'Project Status',
      financialOverview: 'Financial Overview',
      viewFinancial: 'View Financial Report',
      recentActivity: 'Recent Activity',
      viewAll: 'View All',
      noActivityFound: 'No activity found',
      
      // Sidebar
      home: 'Home',
      projects: 'Projects',
      clients: 'Clients',
      employees: 'Employees',
      attendance: 'Attendance',
      tasks: 'Tasks',
      financial: 'Financial',
      settings: 'Settings',
      
      // Projects
      allProjects: 'All Projects',
      searchProjects: 'Search projects...',
      newProject: 'New Project',
      noProjectsFound: 'No projects found',
      fillProjectDetails: 'Fill in the project details below to create a new project',
      projectDetails: 'Project Details',
      projectName: 'Project Name',
      projectNumber: 'Project Number',
      projectDescription: 'Description',
      client: 'Client',
      selectClient: 'Select a client',
      status: 'Status',
      selectStatus: 'Select status',
      planning: 'Planning',
      onTrack: 'On Track',
      atRisk: 'At Risk',
      delayed: 'Delayed',
      onHold: 'On Hold',
      completed: 'Completed',
      startDate: 'Start Date',
      endDate: 'End Date',
      selectDate: 'Select a date',
      budget: 'Budget',
      priority: 'Priority',
      selectPriority: 'Select priority',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      projectType: 'Project Type',
      selectProjectType: 'Select project type',
      development: 'Development',
      design: 'Design',
      marketing: 'Marketing',
      research: 'Research',
      consulting: 'Consulting',
      cancel: 'Cancel',
      createProject: 'Create Project',
      updateProject: 'Update Project',
      saving: 'Saving...',
      projectCreatedSuccess: 'Project created successfully',
      projectCreateError: 'Error creating project',
      error: 'Error',
      errorLoadingProjects: 'Error loading projects',
      errorLoadingClients: 'Error loading clients',
      
      // Tasks
      newTask: 'New Task',
      taskName: 'Task Name',
      assignee: 'Assignee',
      selectAssignee: 'Select assignee',
      dueDate: 'Due Date',
      createTask: 'Create Task',
      noTasksFound: 'No tasks found',
      taskCreatedSuccess: 'Task created successfully',
      errorLoadingTasks: 'Error loading tasks',
      taskCreateError: 'Error creating task',
      filterTasks: 'Filter tasks...',
      taskDetails: 'Task Details',
      
      // Clients
      allClients: 'All Clients',
      searchClients: 'Search clients...',
      newClient: 'New Client',
      noClientsFound: 'No clients found',
      clientName: 'Client Name',
      contactPerson: 'Contact Person',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      clientType: 'Client Type',
      selectClientType: 'Select client type',
      clientStatus: 'Status',
      createClient: 'Create Client',
      
      // Financial
      revenue: 'Revenue',
      expenses: 'Expenses',
      profit: 'Profit',
      pendingInvoices: 'Pending Invoices',
      
      // Employees
      allEmployees: 'All Employees',
      searchEmployees: 'Search employees...',
      newEmployee: 'New Employee',
      noEmployeesFound: 'No employees found',
      employeeName: 'Employee Name',
      position: 'Position',
      department: 'Department',
      joinDate: 'Join Date',
      
      // Attendance
      date: 'Date',
      checkIn: 'Check In',
      checkOut: 'Check Out',
      hoursWorked: 'Hours Worked',
      
      // Settings
      generalSettings: 'General Settings',
      accountSettings: 'Account Settings',
      notificationSettings: 'Notification Settings',
      securitySettings: 'Security Settings',
      
      // Settings related translations
      settings: "Settings",
      settings_description: "Manage your office, users, permissions and preferences",
      office_settings: "Office Settings",
      office_settings_description: "Configure your office information and branding",
      user_management: "User Management",
      user_management_description: "Manage users and their access to the system",
      role_permissions: "Role Permissions",
      role_permissions_description: "Manage permissions for different user roles",
      theme_settings: "Theme Settings",
      theme_settings_description: "Customize the appearance of the application",
      
      // Office settings
      office_name: "Office Name",
      enter_office_name: "Enter office name",
      address: "Address",
      enter_address: "Enter address",
      phone: "Phone",
      enter_phone: "Enter phone",
      email: "Email",
      enter_email: "Enter email",
      website: "Website",
      enter_website: "Enter website",
      description: "Description",
      enter_description: "Enter description",
      office_logo: "Office Logo",
      logo_description: "Upload your office logo (recommended size: 200x200px)",
      save_changes: "Save Changes",
      office_settings_updated: "Office settings updated successfully",
      error_updating_office_info: "Error updating office information",
      error_fetching_office_info: "Error fetching office information",
      logo_uploaded: "Logo uploaded successfully",
      error_uploading_logo: "Error uploading logo",
      
      // User management
      users: "Users",
      add_user: "Add User",
      add_new_user: "Add New User",
      name: "Name",
      enter_name: "Enter name",
      password: "Password",
      enter_password: "Enter password",
      role: "Role",
      select_role: "Select role",
      department: "Department",
      select_department: "Select department",
      status: "Status",
      select_status: "Select status",
      active: "Active",
      inactive: "Inactive",
      edit_user: "Edit User",
      delete_user: "Delete User",
      search_users: "Search users",
      user_added_successfully: "User added successfully",
      user_updated_successfully: "User updated successfully",
      user_deleted_successfully: "User deleted successfully",
      error_fetching_users: "Error fetching users",
      no_users_found: "No users found",
      
      // Roles
      admin: "Administrator",
      manager: "Manager",
      engineer: "Engineer",
      accountant: "Accountant",
      client_manager: "Client Manager",
      employee: "Employee",
      
      // Departments
      management: "Management",
      engineering: "Engineering",
      accounting: "Accounting",
      sales: "Sales",
      hr: "Human Resources",
      it: "IT",
      
      // Permissions
      save_permissions: "Save Permissions",
      permissions_saved: "Permissions saved successfully",
      error_saving_permissions: "Error saving permissions",
      by_module: "By Module",
      permission_matrix: "Permission Matrix",
      permission_view: "View",
      permission_create: "Create",
      permission_edit: "Edit",
      permission_delete: "Delete",
      
      // Theme settings
      appearance: "Appearance",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      system: "System",
      accent_color: "Accent Color",
      select_accent_color: "Select accent color",
      blue: "Blue",
      green: "Green",
      purple: "Purple",
      orange: "Orange",
      red: "Red",
      language: "Language",
      select_language: "Select language",
      accessibility: "Accessibility",
      enable_animations: "Enable Animations",
      enable_animations_description: "Enable animations and transitions in the UI",
      high_contrast_mode: "High Contrast Mode",
      high_contrast_mode_description: "Increase contrast for better readability",
      reduced_motion: "Reduced Motion",
      reduced_motion_description: "Minimize animations for users who prefer less motion",
      save_settings: "Save Settings",
      theme_settings_saved: "Theme settings saved successfully",
      error_saving_theme_settings: "Error saving theme settings",
      
      // Common
      loading: "Loading...",
      saving: "Saving...",
      success: "Success",
      error: "Error",
      cancel: "Cancel",
      save: "Save",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
    },
    ar: {
      // Dashboard
      dashboard: 'لوحة التحكم',
      welcomeBack: 'مرحبًا بعودتك',
      teamActivity: 'نشاط الفريق',
      activeProjects: 'المشاريع النشطة',
      totalClients: 'إجمالي العملاء',
      totalEmployees: 'إجمالي الموظفين',
      pendingTasks: 'المهام المعلقة',
      revenueThisMonth: 'الإيرادات هذا الشهر',
      viewActivity: 'عرض النشاط',
      projectStatus: 'حالة المشروع',
      financialOverview: 'نظرة عامة مالية',
      viewFinancial: 'عرض التقرير المالي',
      recentActivity: 'النشاط الأخير',
      viewAll: 'عرض الكل',
      noActivityFound: 'لم يتم العثور على نشاط',
      
      // Sidebar
      home: 'الرئيسية',
      projects: 'المشاريع',
      clients: 'العملاء',
      employees: 'الموظفين',
      attendance: 'الحضور',
      tasks: 'المهام',
      financial: 'المالية',
      settings: 'الإعدادات',
      
      // Projects
      allProjects: 'جميع المشاريع',
      searchProjects: 'البحث في المشاريع...',
      newProject: 'مشروع جديد',
      noProjectsFound: 'لم يتم العثور على مشاريع',
      fillProjectDetails: 'املأ تفاصيل المشروع أدناه لإنشاء مشروع جديد',
      projectDetails: 'تفاصيل المشروع',
      projectName: 'اسم المشروع',
      projectNumber: 'رقم المشروع',
      projectDescription: 'وصف المشروع',
      client: 'العميل',
      selectClient: 'اختر عميلاً',
      status: 'الحالة',
      selectStatus: 'اختر الحالة',
      planning: 'التخطيط',
      onTrack: 'في المسار',
      atRisk: 'في خطر',
      delayed: 'متأخر',
      onHold: 'معلق',
      completed: 'مكتمل',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ الانتهاء',
      selectDate: 'اختر تاريخًا',
      budget: 'الميزانية',
      priority: 'الأولوية',
      selectPriority: 'اخت�� الأولوية',
      low: 'منخفضة',
      medium: 'متوسطة',
      high: 'عالية',
      urgent: 'عاجلة',
      projectType: 'نوع المشروع',
      selectProjectType: 'اختر نوع المشروع',
      development: 'تطوير',
      design: 'تصميم',
      marketing: 'تسويق',
      research: 'بحث',
      consulting: 'استشارات',
      cancel: 'إلغاء',
      createProject: 'إنشاء مشروع',
      updateProject: 'تحديث المشروع',
      saving: 'جاري الحفظ...',
      projectCreatedSuccess: 'تم إنشاء المشروع بنجاح',
      projectCreateError: 'خطأ في إنشاء المشروع',
      error: 'خطأ',
      errorLoadingProjects: 'خطأ في تحميل المشاريع',
      errorLoadingClients: 'خطأ في تحميل العملاء',
      
      // Tasks
      newTask: 'مهمة جديدة',
      taskName: 'اسم المهمة',
      assignee: 'المكلف',
      selectAssignee: 'اختر المكلف',
      dueDate: 'تاريخ الاستحقاق',
      createTask: 'إنشاء مهمة',
      noTasksFound: 'لم يتم العثور على مهام',
      taskCreatedSuccess: 'تم إنشاء المهمة بنجاح',
      errorLoadingTasks: 'خطأ في تحميل المهام',
      taskCreateError: 'خطأ في إنشاء المهمة',
      filterTasks: 'تصفية المهام...',
      taskDetails: 'تفاصيل المهمة',
      
      // Clients
      allClients: 'جميع العملاء',
      searchClients: 'البحث عن عملاء...',
      newClient: 'عميل جديد',
      noClientsFound: 'لم يتم العثور على عملاء',
      clientName: 'اسم العميل',
      contactPerson: 'الشخص المسؤول',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      location: 'الموقع',
      clientType: 'نوع العميل',
      selectClientType: 'اختر نوع العميل',
      clientStatus: 'الحالة',
      createClient: 'إنشاء عميل',
      
      // Financial
      revenue: 'الإيرادات',
      expenses: 'المصروفات',
      profit: 'الأرباح',
      pendingInvoices: 'الفواتير المعلقة',
      
      // Employees
      allEmployees: 'جميع الموظفين',
      searchEmployees: 'البحث عن موظفين...',
      newEmployee: 'موظف جديد',
      noEmployeesFound: 'لم يتم العثور على موظفين',
      employeeName: 'اسم الموظف',
      position: 'المنصب',
      department: 'القسم',
      joinDate: 'تاريخ الانضمام',
      
      // Attendance
      date: 'التاريخ',
      checkIn: 'تسجيل الدخول',
      checkOut: 'تسجيل الخروج',
      hoursWorked: 'ساعات العمل',
      
      // Settings
      generalSettings: 'الإعدادات العامة',
      accountSettings: 'إعدادات الحساب',
      notificationSettings: 'إعدادات الإشعارات',
      securitySettings: 'إعدادات الأمان',
      
      // Settings related translations
      settings: "الإعدادات",
      settings_description: "إدارة المكتب والمستخدمين والصلاحيات والتفضيلات",
      office_settings: "إعدادات المكتب",
      office_settings_description: "تكوين معلومات المكتب والعلامة التجارية",
      user_management: "إدارة المستخدمين",
      user_management_description: "إدارة المستخدمين وصلاحياتهم في النظام",
      role_permissions: "صلاحيات الأدوار",
      role_permissions_description: "إدارة صلاحيات مختلف أدوار المستخدمين",
      theme_settings: "إعدادات المظهر",
      theme_settings_description: "تخصيص مظهر التطبيق",
      
      // Office settings
      office_name: "اسم المكتب",
      enter_office_name: "أدخل اسم المكتب",
      address: "العنوان",
      enter_address: "أدخل العنوان",
      phone: "الهاتف",
      enter_phone: "أدخل رقم الهاتف",
      email: "البريد الإلكتروني",
      enter_email: "أدخل البريد الإلكتروني",
      website: "الموقع الإلكتروني",
      enter_website: "أدخل الموقع الإلكتروني",
      description: "الوصف",
      enter_description: "أدخل الوصف",
      office_logo: "شعار المكتب",
      logo_description: "قم بتحميل شعار المكتب (الحجم الموصى به: 200×200 بكسل)",
      save_changes: "حفظ التغييرات",
      office_settings_updated: "تم تحديث إعدادات المكتب بنجاح",
      error_updating_office_info: "خطأ في تحديث معلومات المكتب",
      error_fetching_office_info: "خطأ في جلب معلومات المكتب",
      logo_uploaded: "تم تحميل الشعار بنجاح",
      error_uploading_logo: "خطأ في تحميل الشعار",
      
      // User management
      users: "المستخدمين",
      add_user: "إضافة مستخدم",
      add_new_user: "إضافة مستخدم جديد",
      name: "الاسم",
      enter_name: "أدخل الاسم",
      password: "كلمة المرور",
      enter_password: "أدخل كلمة المرور",
      role: "الدور",
      select_role: "اختر الدور",
      department: "القسم",
      select_department: "اختر القسم",
      status: "الحالة",
      select_status: "اختر الحالة",
      active: "نشط",
      inactive: "غير نشط",
      edit_user: "تعديل المستخدم",
      delete_user: "حذف المستخدم",
      search_users: "بحث عن مستخدمين",
      user_added_successfully: "تمت إضافة المستخدم بنجاح",
      user_updated_successfully: "تم تحديث المستخدم بنجاح",
      user_deleted_successfully: "تم حذف المستخدم بنجاح",
      error_fetching_users: "خطأ في جلب المستخدمين",
      no_users_found: "لم يتم العثور على مستخدمين",
      
      // Roles
      admin: "مدير النظام",
      manager: "مدير",
      engineer: "مهندس",
      accountant: "محاسب",
      client_manager: "مدير العملاء",
      employee: "موظف",
      
      // Departments
      management: "الإدارة",
      engineering: "الهندسة",
      accounting: "المحاسبة",
      sales: "المبيعات",
      hr: "الموارد البشرية",
      it: "تكنولوجيا المعلومات",
      
      // Permissions
      save_permissions: "حفظ الصلاحيات",
      permissions_saved: "تم حفظ الصلاحيات بنجاح",
      error_saving_permissions: "خطأ في حفظ الصلاحيات",
      by_module: "حسب الوحدة",
      permission_matrix: "مصفوفة الصلاحيات",
      permission_view: "عرض",
      permission_create: "إنشاء",
      permission_edit: "تعديل",
      permission_delete: "حذف",
      
      // Theme settings
      appearance: "المظهر",
      theme: "السمة",
      light: "فاتح",
      dark: "داكن",
      system: "نظام",
      accent_color: "لون التمييز",
      select_accent_color: "اختر لون التمييز",
      blue: "أزرق",
      green: "أخضر",
      purple: "بنفسجي",
      orange: "برتقالي",
      red: "أحمر",
      language: "اللغة",
      select_language: "اختر اللغة",
      accessibility: "إمكانية الوصول",
      enable_animations: "تمكين الرسوم المتحركة",
      enable_animations_description: "تمكين الرسوم المتحركة والانتقالات في الواجهة",
      high_contrast_mode: "وضع التباين العالي",
      high_contrast_mode_description: "زيادة التباين لتحسين القراءة",
      reduced_motion: "تقليل الحركة",
      reduced_motion_description: "تقليل الرسوم المتحركة للمستخدمين الذين يفضلون حركة أقل",
      save_settings: "حفظ الإعدادات",
      theme_settings_saved: "تم حفظ إعدادات المظهر بنجاح",
      error_saving_theme_settings: "خطأ في حفظ إعدادات المظهر",
      
      // Common
      loading: "جاري التحميل...",
      saving: "جاري الحفظ...",
      success: "نجاح",
      error: "خطأ",
      cancel: "إلغاء",
      save: "حفظ",
      actions: "إجراءات",
      edit: "تعديل",
      delete: "حذف",
    },
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
